In [2]:
import numpy as np

## Np.array()

In [31]:
numbers = [[2, 3, 4, 5], [7, 2, 5, 0]] # Lista bidimensional
data_type = "int" # Tipo de dados do array
a_array = np.array(numbers, data_type) # Converte a lista em array com dados do tipo int
a_array

array([[2, 3, 4, 5],
       [7, 2, 5, 0]])

In [29]:
b_array = np.array(a_array, "bool") # Converte os dados do array em floats/bool ou str
b_array

array([[ True,  True,  True,  True],
       [ True,  True,  True, False]])

Existem muitos outros tipos de dados que podem ser especificados no parâmetro dtype do método np.array() do NumPy. Aqui estão alguns exemplos adicionais:

    complex: para números complexos
    object: para objetos Python
    datetime64: para objetos de data e hora
    timedelta64: para objetos de diferença de tempo
    category: para variáveis categóricas

Além disso, o NumPy também oferece suporte a tipos de dados especializados, como float16, float32, float64, int8, int16, int32, int64, etc. Você pode ver a lista completa de tipos de dados suportados pelo NumPy na documentação do NumPy.

In [31]:
new_data_type = "object"
c_array = np.array(b_array, new_data_type)
c_array

array([[True, True, True, True],
       [True, True, True, False]], dtype=object)

O método np.array() do NumPy aceita vários parâmetros diferentes que podem ser usados para controlar a criação de um array. Aqui estão alguns dos principais parâmetros que podem ser passados para o método np.array():

    object: um objeto Python que será convertido em um array NumPy. Isso pode ser uma lista, tupla, matriz, etc.
    dtype: o tipo de dados dos elementos no array. Por exemplo, float, int, bool, etc.
    copy: um valor lógico que indica se o array deve ser copiado ou apenas visto como um vista do objeto original.
    order: o ordenamento dos elementos no array. As opções são 'C' para uma ordem de armazenamento C-style ou 'F' para uma ordem de armazenamento Fortran-style. (o primeiro faz o programa ler linha por linha, e no segundo ele lê coluna por coluna)
    subok: um valor lógico que indica se os objetos herdados devem ser retornados como objetos ou se devem ser convertidos em arrays NumPy.
    offset: um inteiro que indica a posição do primeiro elemento no buffer.

In [60]:
d_array = np.array(object=numbers, dtype="int", copy=True, order="F", subok=False)
d_array

array([[2, 3, 4, 5],
       [7, 2, 5, 0]])

Uma instância do método np.array() do NumPy possui vários atributos que podem ser usados para visualizar as informações do array. Aqui estão alguns exemplos de atributos comuns que podem ser passados para a instância de np.array():

    shape: usado para especificar a forma (dimensões) do array
    size: usado para especificar o número total de elementos no array
    itemsize: usado para especificar o tamanho em bytes de cada elemento no array
    strides: usado para especificar o número de bytes que o array avança ao acessar cada elemento

In [52]:
e_array = np.array(numbers, "int")
e_array

array([[2, 3, 4, 5],
       [7, 2, 5, 0]])

In [53]:
print(e_array.shape) 
print(e_array.size) 
print(e_array.ndim) 
print(e_array.itemsize) 
print(e_array.strides)

(2, 4)
8
2
4
(16, 4)


#### Alteração de dados do array


In [76]:
data = [[27, 21, 48, 34], [55, 71, 20, 46]]
f_array = np.array(data, dtype="int")
f_array[0, 1] = 120 # Altera o valor da linha 0 e coluna 1
f_array

array([[ 27, 120,  48,  34],
       [ 55,  71,  20,  46]])

In [83]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [91]:
g_array = np.array(data, dtype="int", copy=True, order="F", subok=False, ndmin=1, like=f_array) # like: mesma forma e tipo de dados
g_array

array([[27, 21, 48, 34],
       [55, 71, 20, 46]])

In [103]:
ones_array = np.ones_like(g_array)
zeros_array = np.zeros_like(g_array)
full_array = np.full_like(g_array, 7)
ones = np.ones((2, 2), dtype="int")
zeros = np.zeros((2, 2), dtype="int")
fulls = np.full((2, 3), 9, dtype="int")

print(ones_array)
print("---------")
print(zeros_array)
print("---------")
print(full_array)
print("---------")
print(ones)
print("---------")
print(zeros)
print("---------")
print(fulls)

[[1 1 1 1]
 [1 1 1 1]]
---------
[[0 0 0 0]
 [0 0 0 0]]
---------
[[7 7 7 7]
 [7 7 7 7]]
---------
[[1 1]
 [1 1]]
---------
[[0 0]
 [0 0]]
---------
[[9 9 9]
 [9 9 9]]


## Np.arange()

In [4]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [3]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(3.0)

array([0., 1., 2.])

In [5]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [6]:
np.arange(20, dtype='complex')

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])

In [7]:
np.arange(1, 10, 2, dtype="float")

array([1., 3., 5., 7., 9.])

## Np.linspace

O método linspace() do NumPy é usado para criar um array NumPy com um número especificado de elementos igualmente distribuídos entre um intervalo especificado. Ele é muito útil para criar arrays de valores de referência para ajuste de curvas, gráficos e outras tarefas.

Onde:

    start: o valor inicial do intervalo
    stop: o valor final do intervalo
    num: o número de elementos no array (opcional, o padrão é 50)
    endpoint: se o valor final deve ou não ser incluído no array (opcional, o padrão é True)
    retstep: se o passo entre os elementos do array deve ser retornado (opcional, o padrão é False)
    dtype: o tipo de dados dos elementos do array (opcional)
    axis: a dimensão do array (opcional, o padrão é 0)

In [29]:
h_array = np.linspace(start=4, stop=10, num=20, endpoint=False, retstep=False, dtype="int", axis=0)
h_array

array([4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 9, 9, 9])

In [39]:
i_array = np.linspace(1, 100, num=5, dtype="int", retstep=True)
# Retstep é o valor do intervalo 
j_array = np.linspace(1, 100, num=5, dtype="float", endpoint=False, retstep=True)
print(i_array)
print(j_array)

(array([  1,  25,  50,  75, 100]), 24.75)
(array([ 1. , 20.8, 40.6, 60.4, 80.2]), 19.8)


## Eye Function

In [49]:
k_array = np.eye(5, 5, k=0, dtype="int", order='C')
k_array

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [50]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random function

O método rand() do módulo random do NumPy é usado para gerar números aleatórios a partir de uma distribuição uniforme [0, 1]. Ele pode ser usado para criar arrays de números aleatórios de qualquer forma ou tamanho.

In [51]:
np.random.rand(5)

array([0.07603145, 0.83020034, 0.85181087, 0.76554816, 0.28340856])

In [52]:
np.random.rand(5, 4)

array([[0.32967026, 0.49827887, 0.66392089, 0.81514374],
       [0.02220377, 0.55970669, 0.61196506, 0.28994342],
       [0.64222227, 0.88355504, 0.31586727, 0.71372139],
       [0.39822669, 0.07865583, 0.05609973, 0.61159316],
       [0.65524831, 0.74414739, 0.77878139, 0.13742569]])

O método randn() do módulo random do NumPy é usado para gerar números aleatórios a partir de uma distribuição normal padrão (média 0 e desvio padrão 1). Ele pode ser usado para criar arrays de números aleatórios de qualquer forma ou tamanho.

In [53]:
np.random.randn(5)

array([-0.83933027,  1.52304298, -1.2660275 ,  0.89996051,  1.85121498])

In [54]:
np.random.randn(5, 4)

array([[-1.44028883, -0.81277127,  0.24281204, -1.32260726],
       [ 0.4178355 ,  2.06701633,  1.46162108, -2.37518448],
       [-0.35515355, -0.16990357, -0.9669727 ,  0.61892248],
       [ 0.54509412,  0.16922089,  0.36740023,  1.85580139],
       [-0.03746578, -0.66170124,  1.2311993 ,  0.12337921]])

O método ranf() do módulo random do NumPy é usado para gerar números aleatórios flutuantes uniformemente distribuídos entre 0 e 1. Ele pode ser usado para criar arrays de números aleatórios de qualquer forma ou tamanho.

In [59]:
np.random.ranf(5)

array([0.34256501, 0.43675641, 0.81638223, 0.2690172 , 0.24591046])

In [71]:
l_array = sorted(np.unique(np.random.randint(1, 60, 6, dtype="int")))
l_array

[3, 6, 9, 24, 31, 51]