In [8]:
import numpy as np
import tensorflow as tf

In [11]:
# Criando váriaveis com tensorflow
string = tf.Variable("My String", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [14]:
# Graus de Vetores/ou tensors
rank1_tensor = tf.Variable(['Test'], tf.string) # 1 dimensão 
rank2_tensor = tf.Variable([["Test", "ok"], ["test", "yes"]], tf.string) # 2 dimensões

### Acesso a dimensões e formatos

In [15]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [16]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [17]:
rank1_tensor.shape

TensorShape([1])

In [18]:
rank2_tensor.shape

TensorShape([2, 2])

### Alterando formatos

In [19]:
# A quantidade de números dentro da lista corresponde ao número de dimensões 
tensor1 = tf.ones([1, 2, 3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [33]:
other_tensor = tf.ones([5]) # 5 sendo a quantidade de números 1
print(other_tensor)

tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float32)


In [34]:
other_tensor2 = tf.ones([5, 5])
print(other_tensor2)

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(5, 5), dtype=float32)


In [35]:
other_tensor3 = tf.ones([5, 5, 5])
other_tensor3

<tf.Tensor: shape=(5, 5, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [41]:
tensor2 = tf.reshape(tensor1, [2, 3, 1])
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
